In [1]:
import pandas as pd
import os

path = "CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [2]:
# 4 - Leitura da tabela
bruto = pd.read_excel(path, header=None)
bruto.head(10)

,0,1,2,3,4,5,6,7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Censo Demográfico 2022: População e Domicílios...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
3,NaN,RO,11,00015,Alta Floresta D'Oeste,24392,24392,21494
4,NaN,RO,11,00023,Ariquemes,90353,90353,96833
5,NaN,RO,11,00031,Cabixi,6313,6313,5351
6,NaN,RO,11,00049,Cacoal,78574,78574,86887
7,NaN,RO,11,00056,Cerejeiras,17029,17029,15890
8,NaN,RO,11,00064,Colorado do Oeste,18591,18591,15663
9,NaN,RO,11,00072,Corumbiara,8783,8783,7519

In [3]:
dados = bruto.iloc[3:5573].copy().reset_index(drop=True)
dados = dados.drop(columns=[0])

colunas = ["uf", "cod_uf", "cod_munic", "municipio", "pop_2010_sinopse", "pop_2010_compatibilizada", "pop_2022"]
dados.columns = colunas

for c in ["cod_uf", "pop_2010_sinopse", "pop_2010_compatibilizada", "pop_2022"]:
    dados[c] = pd.to_numeric(dados[c], errors="coerce")

dados.head(10)

,uf,cod_uf,cod_munic,municipio,pop_2010_sinopse,pop_2010_compatibilizada,pop_2022
0,RO,11,00015,Alta Floresta D'Oeste,24392,24392,21494
1,RO,11,00023,Ariquemes,90353,90353,96833
2,RO,11,00031,Cabixi,6313,6313,5351
3,RO,11,00049,Cacoal,78574,78574,86887
4,RO,11,00056,Cerejeiras,17029,17029,15890
5,RO,11,00064,Colorado do Oeste,18591,18591,15663
6,RO,11,00072,Corumbiara,8783,8783,7519
7,RO,11,00080,Costa Marques,13678,13678,12627
8,RO,11,00098,Espigão D'Oeste,28729,28729,29414
9,RO,11,00106,Guajará-Mirim,41656,41656,39387

In [4]:
# 5 - Tabela de população agregada por estado
pop_por_estado = (
    dados.groupby("uf")[["pop_2010_compatibilizada", "pop_2022"]]
    .sum()
    .reset_index()
)
pop_por_estado

    uf  pop_2010_compatibilizada  pop_2022
0   AC                    733559    830018
1   AL                   3120887   3127683
2   AM                   3483985   3941613
3   AP                    669526    733759
4   BA                  14017071  14141626
5   CE                   8451644   8794957
6   DF                   2572159   2817381
7   ES                   3514952   3833712
8   GO                   6001789   7056495
9   MA                   6574789   6776699
10  MG                  19597330  20539989
11  MS                   2449024   2757013
12  MT                   3035122   3658649
13  PA                   7581051   8120131
14  PB                   3766528   3974687
15  PE                   8796055   9058931
16  PI                   3119097   3271199
17  PR                  10444526  11444380
18  RJ                  15989929  16055174
19  RN                   3168027   3302729
20  RO                   1562409   1581196
21  RR                    450479    636707
22  RS                  10693929  10882965
23  SC                   6248436   7610361
24  SE                   2067852   2210004
25  SP                  41262199  44411238
26  TO                   1383445   1511460

In [5]:
# 6 - Organizar por população que mais cresceu entre 2010 e 2022 (estado)
pop_por_estado["crescimento_absoluto"] = pop_por_estado["pop_2022"] - pop_por_estado["pop_2010_compatibilizada"]
pop_por_estado = pop_por_estado.sort_values("crescimento_absoluto", ascending=False).reset_index(drop=True)
pop_por_estado

    uf  pop_2010_compatibilizada  pop_2022  crescimento_absoluto
0   SP                  41262199  44411238               3149039
1   SC                   6248436   7610361               1361925
2   GO                   6001789   7056495               1054706
3   PR                  10444526  11444380                999854
4   MG                  19597330  20539989                942659
5   MT                   3035122   3658649                623527
6   PA                   7581051   8120131                539080
7   AM                   3483985   3941613                457628
8   CE                   8451644   8794957                343313
9   ES                   3514952   3833712                318760
10  MS                   2449024   2757013                307989
11  PE                   8796055   9058931                262876
12  DF                   2572159   2817381                245222
13  PB                   3766528   3974687                208159
14  MA                   6574789   6776699                201910
15  RS                  10693929  10882965                189036
16  RR                    450479    636707                186228
17  PI                   3119097   3271199                152102
18  SE                   2067852   2210004                142152
19  RN                   3168027   3302729                134702
20  TO                   1383445   1511460                128015
21  BA                  14017071  14141626                124555
22  AC                    733559    830018                 96459
23  RJ                  15989929  16055174                 65245
24  AP                    669526    733759                 64233
25  RO                   1562409   1581196                 18787
26  AL                   3120887   3127683                  6796

In [6]:
# 7 - Salvar tabela por estado em csv
nome_arquivo_estado = "populacao_por_estado_crescimento"
caminho_estado = os.path.join(os.getcwd(), f"{nome_arquivo_estado}.csv")
pop_por_estado.to_csv(caminho_estado, sep=";", index=False)

In [7]:
# 8 - Trabalhar por município
pop_por_municipio = dados[["uf", "municipio", "pop_2010_compatibilizada", "pop_2022"]].copy()
pop_por_municipio.head(10)

   uf              municipio  pop_2010_compatibilizada  pop_2022
0  RO  Alta Floresta D'Oeste                     24392     21494
1  RO              Ariquemes                     90353     96833
2  RO                 Cabixi                      6313      5351
3  RO                 Cacoal                     78574     86887
4  RO             Cerejeiras                     17029     15890
5  RO      Colorado do Oeste                     18591     15663
6  RO             Corumbiara                      8783      7519
7  RO          Costa Marques                     13678     12627
8  RO        Espigão D'Oeste                     28729     29414
9  RO          Guajará-Mirim                     41656     39387

In [8]:
# 9 - Organizar por população que mais cresceu entre 2010 e 2022 (município)
pop_por_municipio["crescimento_absoluto"] = pop_por_municipio["pop_2022"] - pop_por_municipio["pop_2010_compatibilizada"]
pop_por_municipio = pop_por_municipio.sort_values("crescimento_absoluto", ascending=False).reset_index(drop=True)
pop_por_municipio.head(10)

   uf      municipio  pop_2010_compatibilizada  pop_2022  crescimento_absoluto
0  AM         Manaus                   1802014   2063689                261675
1  DF       Brasília                   2572159   2817381                245222
2  SP      São Paulo                  11253503  11451999                198496
3  SP       Sorocaba                    586816    723682                136866
4  GO        Goiânia                   1301912   1437366                135454
5  RR      Boa Vista                    284313    413486                129173
6  SC  Florianópolis                    421240    537211                115971
7  PA    Parauapebas                    153908    267836                113928
8  MS   Campo Grande                    786774    898100                111326
9  PB    João Pessoa                    723515    833932                110417

In [9]:
# 10 - Salvar tabela por município em csv
nome_arquivo_municipio = "populacao_por_municipio_crescimento"
caminho_municipio = os.path.join(os.getcwd(), f"{nome_arquivo_municipio}.csv")
pop_por_municipio.to_csv(caminho_municipio, sep=";", index=False)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

fig, ax = plt.subplots(figsize=(9, 8))
ordem = pop_por_estado.sort_values("pop_2022", ascending=False)
sns.barplot(data=ordem, y="uf", x="pop_2022", ax=ax, color="steelblue")
ax.set_title("População 2022 por UF")
ax.set_xlabel("Habitantes")
ax.set_ylabel("UF")
plt.tight_layout()
plt.show()